# 1) Introduction of PyTorch Tensors and Basic Operations
a) PyTorch Tensors: Initialization & Data Types

In [ ]:
import torch

a = torch.tensor([1, 2, 3])
print(a)

b = torch.zeros((2,3))
c = torch.zeros((3,3))

d = torch.rand((2,2))

e = torch.tensor([1,2,3], dtype=torch.float32)
print(b, c, d, e)

# Common Data Types
# torch.int32, torch.float32, torch.float64, torch.bool

tensor([1, 2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[0.3393, 0.5335],
        [0.5261, 0.0173]]) tensor([1., 2., 3.])


b) Tensor Operations

In [ ]:
# Arithmetic Operation
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print(x + y)
print(x * y)
print(torch.add(x, y))


# Broadcasting
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

b = torch.tensor([1, 2, 3])

print(a + b)

# Indexing & Slicing
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(t[0])        # First row
print(t[:, 1])     # Second column
print(t[1, 2])     # Specific element

# Reshaping

x = torch.arange(12)
y = x.view(3, 4)
z = x.reshape(2, 6)

print(y)
print(z)


tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([5, 7, 9])
tensor([[2, 4, 6],
        [5, 7, 9]])
tensor([1, 2, 3])
tensor([2, 5])
tensor(6)
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


c) Automatic Differentiation (Autograd)

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 2*x

y.backward()
print(x.grad)

tensor(14.)


# 2) Linear Algebra Operations using TensorFlow

In [ ]:
import tensorflow as tf

A = tf.constant([[1,2],[3,4]], dtype = tf.float32)
B = tf.constant([[5,6],[7,8]], dtype = tf.float32)

print(tf.add(A, B))
print(tf.subtract(A, B))

print(tf.matmul(A, B))
print(tf.transpose(A))
print(tf.linalg.inv(A))
eigenvalues = tf.linalg.eig(A)
print(eigenvalues)



tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
(<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.37228122+0.j,  5.372281  +0.j], dtype=complex64)>, <tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[-0.8245648 +0.j, -0.41597357+0.j],
       [ 0.56576747+0.j, -0.90937674+0.j]], dtype=complex64)>)


# 3) AND & OR Gates using Perceptron

In [ ]:
def perceptron(x1, x2, w1, w2, b):
  y = x1*w1 + x2*w2 + b
  return 1 if y >= 0 else 0

print("AND GATE")
for x1 in [0,1]:
  for x2 in [0,1]:
    print(x1, x2, perceptron(x1, x2, 1, 1, -1.5))

print("OR GATE")
for x1 in [0,1]:
  for x2 in [0,1]:
    print(x1, x2, perceptron(x1, x2, 1, 1, -0.5))

AND GATE
0 0 0
0 1 0
1 0 0
1 1 1
OR GATE
0 0 0
0 1 1
1 0 1
1 1 1


# 4) XOR Problem using PyTorch Neural Network

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

X = torch.tensor([[0., 0.],
                  [0., 1.],
                  [1., 0.],
                  [1., 1.]])

y = torch.tensor([[0.],
                  [1.],
                  [1.],
                  [0.]])

class XORNet(nn.Module):
  def __init__(self):
    super(XORNet, self).__init__()
    self.fc1 = nn.Linear(2, 4)
    self.fc2 = nn.Linear(4, 1)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    x = torch.sigmoid(self.fc2(x))
    return x

model = XORNet()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

for epoch in range(2000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

with torch.no_grad():
    predictions = model(X)
    print(torch.round(predictions))


Epoch 0, Loss: 0.7071200609207153
Epoch 400, Loss: 0.4773862063884735
Epoch 800, Loss: 0.47738614678382874
Epoch 1200, Loss: 0.4773860275745392
Epoch 1600, Loss: 0.4773859977722168
tensor([[1.],
        [1.],
        [1.],
        [0.]])


# 5) Implement Simple below Neural Network to solve regression problem.

In [ ]:
import numpy as np
import pandas as pd


# Load & Preprocess Data

path = "/content/house_price_full+(2) - house_price_full+(2).csv"
df = pd.read_csv(path)

data = df.values
X = data[:, :-1]
y = data[:, -1].reshape(-1, 1)

# Normalize
X = (X - X.mean(axis=0)) / X.std(axis=0)
y = (y - y.mean()) / y.std()


# Activation Functions

def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)



np.random.seed(42)

W1 = np.random.randn(X.shape[1], 2)
b1 = np.zeros((1, 2))

W2 = np.random.randn(2, 1)
b2 = np.zeros((1, 1))

learning_rate = 0.01




def forward(X):
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)
    z2 = np.dot(a1, W2) + b2
    return z1, a1, z2


# Loss Function (MSE)

def mse(y, y_hat):
    return np.mean((y - y_hat) ** 2)

# Backpropagation

def backward(X, y, z1, a1, y_hat):
    global W1, b1, W2, b2
    m = X.shape[0]

    dz2 = y_hat - y
    dW2 = np.dot(a1.T, dz2) / m
    db2 = np.mean(dz2, axis=0, keepdims=True)

    da1 = np.dot(dz2, W2.T)
    dz1 = da1 * relu_derivative(z1)
    dW1 = np.dot(X.T, dz1) / m
    db1 = np.mean(dz1, axis=0, keepdims=True)

    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1


# Training Loop

epochs = 3000

for epoch in range(epochs):
    z1, a1, y_hat = forward(X)
    loss = mse(y, y_hat)
    backward(X, y, z1, a1, y_hat)

    if epoch % 300 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")



sample = X[0].reshape(1, -1)
_, _, prediction = forward(sample)

print("\nPrediction (normalized):", prediction)
print("Actual (normalized):", y[0])


Epoch 0, Loss: 1.8087
Epoch 300, Loss: 0.5351
Epoch 600, Loss: 0.5266
Epoch 900, Loss: 0.5216
Epoch 1200, Loss: 0.5177
Epoch 1500, Loss: 0.5152
Epoch 1800, Loss: 0.5133
Epoch 2100, Loss: 0.5119
Epoch 2400, Loss: 0.5105
Epoch 2700, Loss: 0.5091

Prediction (normalized): [[-0.42579837]]
Actual (normalized): [-0.68877874]
